### ISSUE TITLE
<title> tag is not closed

### ISSUE THREAD

**Issue by aheneneu** [surprisetalk/worstpress#1]
Title tag is not closed after %s. Should be like this:
 ```
<title>%s</title>
```

P.S.: This is my first bug report on GitHub! 😅

**Comment by surprisetalk** [comment]
https://github.com/surprisetalk/worstpress/commit/80b8faaf769b590c27b7a4bb24193b5239c121f6

**Comment by surprisetalk** [comment]
@aheneneu Congrats on your first bug report :)

**Comment by aheneneu** [comment]
@surprisetalk thanks! It's an honor to cuntribute to one of your amazing projects 👍
