### ISSUE TITLE
watch doesn't work

### ISSUE THREAD

**Issue by aheneneu** [surprisetalk/worstpress#3]
https://github.com/surprisetalk/worstpress/blob/906871bf61ec92f14b92b931b2eb7007ca5594b3/readme.md?plain=1#L33

The command results with:

```
Every 2.0s: *.html -p src/* -c ./build.sh
sh: template.html: command not found
```

I have _watch from procps-ng 4.0.3_ installed on MacOS using Homebrew 4.1.1

**Comment by aheneneu** [comment]
I found out a solution to make `watch` continiously monitor a folder and execute commands [here](https://www.baeldung.com/linux/command-execute-file-dir-change). This is my version of the script:

```
#!/bin/bash 
DIR_TO_WATCH=${1}
COMMAND=${2}
trap "echo Exit!; exit;" SIGINT SIGTERM
while [[ 1=1 ]]
do
  watch --chgexit -n 1 "ls -alrf ${DIR_TO_WATCH} | shasum" && ${COMMAND}
  sleep 1
done
```
The difference is that it uses `ls -alrf` and `shasum` commands, which are both compatabile with MacOS 13.4.1.

**Comment by surprisetalk** [comment]
Thanks for looking into this!

Can you show me the output of the following two commands?

```
watch -p "*.html" -p "src/*" -c "./build.sh" 
```

```
./build.sh
```

**Comment by aheneneu** [comment]
As I mentioned before, running watch with parameters results with this:

```
Every 2.0s: *.html -p src/* -c ./build.sh                                            mbp.local: Thu Jul 27 00:15:56 2023

sh: template.html: command not found
```

build.sh provides no output, but it successfully builds html files in dist/ folder based on files in src/.

**Comment by surprisetalk** [comment]
Ah. I installed `watch` like this:

```
brew install watch
```

Did you install it like this?

```
brew install procps-ng
```

We might be using different programs.

**Comment by aheneneu** [comment]
I did it exactly with `brew install watch` too.
`watch -v` returns: "watch from procps-ng 4.0.3".

**Comment by surprisetalk** [comment]
Wow, this was totally my fault -- I figured it out.

```
~ ls -lAsh /opt/homebrew/bin/wat*
0 lrwxr-xr-x@ 1 taylor  admin    39B May 12 08:02 /opt/homebrew/bin/watch -> ../lib/node_modules/watch-cli/bin/watch
```

No clue why my homebrew is linking to npm files!

Looks like the `watch` I was using was actually from `npm i watch-cli`.

Going to update the readme accordingly.

Thanks for your patience!
